name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master, next-js-version]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Verify images exist
        run: |
          echo "Checking public/images directory:"
          ls -la public/images
          
      - name: Build
        env:
          NODE_ENV: production
        run: npm run build

      - name: Check build output
        run: |
          echo "Checking out/images directory:"
          ls -la out/images

      - name: Add .nojekyll file
        run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true 